[build]
  command = "npm run build"
  publish = "public"
  functions = "functions"

[dev]
  autoLaunch = false

[[plugins]]
  package = "netlify-plugin-toast-cache"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
